# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'ChatApp' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ChatApp
  pod 'JSQMessagesViewController'

  target 'ChatAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ChatAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
